### ISSUE TITLE
Unable to run documentation example

### ISSUE THREAD

**Issue by KrAsH-CoD3** [Kaliiiiiiiiii-Vinyzu/CDP-Patches#9]
HI, authors, this is an amazing project thank you!
I am however unable to integrate CDP-Patches with playwright.
I tried the given code at the [CDP-Patches documentation] but it reverted to a type error.
I do have playwright and the browsers installed.

`
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
isinstance() arg 2 must be a type, a tuple of types, or a union
  File "C:\Users\User\Documents\cdp-patches\pw_venv\Lib\site-packages\cdp_patches\input\browsers.py", line 163, in get_async_browser_pid
    if isinstance(browser, DriverlessAsyncChrome):
`

cdp version  = 1.0.1
playwright = 1.43.0

[CDP-Patches documentation]: <https://vinyzu.gitbook.io/cdp-patches-documentation/input/playwright-usage#async-usage-async-playwright-botright>

**Comment by kaliiiiiiiiii** [comment]
dublicate to https://github.com/Kaliiiiiiiiii-Vinyzu/CDP-Patches/issues/10 , sorry only noticed now. Will be fixed
